### ISSUE TITLE
as I can implement push method?

### ISSUE THREAD

**Issue by cdiaz** [hashme/firebase-python#3]
as I can implement push method?

**Comment by elvis-hp** [comment]
HTTPError: 401 Client Error: Unauthorized for url: https://s-usc1c-nss-124.firebaseio.com/.json?ns=my_app-1470372118376&sse=true****

**Comment by shariq** [comment]
Merged a PR for push method.

@hoangphuong: Firebase changed default permission settings so you'll need to make your Firebase public read for the web socket to work.
