### ISSUE TITLE
Subscribe Callback not being initiated

### ISSUE THREAD

**Issue by 0xPBIT** [hashme/firebase-python#6]
When attempting to use the subscriber thread for callback responses to database changes, nothing happens. 

running something like this yields nothing:
```
S = firebaseclient.subscriber(URL, pprint)
S.start()
```

However, using that same URL for a get request works fine:

```
result = firebaseclient.get(URL)
pprint(result)
```

> '-LKbe7DJaA9mKL11Xeoo': {'action': 'start', 'time': '8/23/18, 11:40:21 AM'},
>  '-LKbe7RO_LBRxn68ys_T': {'action': 'finish', 'time': '8/23/18, 11:40:22 AM'}

What might be going wrong with my implementation?

**Comment by lgozalvez** [comment]
Hey, I have the same issue... @shariq can you help?

**Comment by lgozalvez** [comment]
Ok, I've found the issue (at least in my situation). In my case the callback was ok but all the data was coming in big chunks (the code to autocalculate the size of the package is not working with firebase). The solutions is to add the chunksize to the call

    def run(self):
        try:
            self.sse = ClosableSSEClient(self.URL, chunk_size=32)
            for msg in self.sse:
                msg_test = json.loads(msg.data)
                if msg_test is None:    # keep-alives
                    continue
                msg_data = json_to_dict(msg.data)
                msg_event = msg.event
                # TODO: update parent cache here
                self.function((msg.event, msg_data))
        except socket.error:
            pass    # this can happen when we close the stream
        except KeyboardInterrupt:
            self.close()

**Comment by shariq** [comment]
Thank you @lgozalvez !! Sorry I'm no longer actively maintaining this repo
